### PR TITLE
Add Doxygen documentation comments and setup Doxygen

### PR DESCRIPTION
**Pull request by felix-elugbaju**
Comments in doxygen syntax is necessary for deliverable 4 part 3.

### CODE REVIEW

**Review by AlviJawad — CHANGES_REQUESTED** [review]
These changes are mostly okay, but not all functions have their parameters defined. Also, please use param[in], param[in/out], and param[out] when writing parameters.

**Review by johnjegede — APPROVED** [review]
nice comments

**Review by Isaac-Wiebe — APPROVED** [review]
Implement the changes for now, will recheck as functions are modified, as needed.

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
Please resolve all conflicts before any attempted merge.

**Review by AlviJawad — CHANGES_REQUESTED** [review]
Really nice changes, please just resolve the apparent conflict with the object.h file

**Comment by felix-elugbaju** [comment]
> Really nice changes, please just resolve the apparent conflict with the object.h file

I can't find a conflict with the `object.h` file here. What do you think?

**Comment by AlviJawad** [comment]
You just resolved it right now. Good work!

**Review by AlviJawad — APPROVED** [review]

**Pull request merged**
