### PR TITLE
fixed puzzle and added a few test and editted the makefile

### PR DESCRIPTION
**Pull request by johnjegede**

### CODE REVIEW

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
Please call check_stagex() function upon completion of your puzzles.

**Review by AlviJawad — CHANGES_REQUESTED** [review]
please make object descriptions consistent; "a treasure_chest of gold" suggests that that object has the tag "gold", not "treasure_chest".

Also, this is a game and the user can enter any input that they want, you have to deal with the user entering small letter instead of capital (we cannot ask them to enter only capitals)--> there should not be any "Please enter only capital letter statements", please perform proper input handling, see other puzzles for reference.

**Comment by AlviJawad** [comment]
Also, please enter intuitive messages other than PASS and FAIL. Additionally, your first puzzle does not tell the user that the input needs to be entered in a 3-letter word form. The user may try to enter single letters that should be dealt with. That's not how other puzzles work. Please implement these changes so we can tag this as release 1 as soon as possible.

**Review by AlviJawad — APPROVED** [review]

**Comment by AlviJawad** [comment]
Most problems with puzzle 3 fixed, merging to development

**Pull request merged**
