### PR TITLE
All successful puzzle completions should now use the new helper function

### PR DESCRIPTION
**Pull request by AlviJawad**
Use check_solved_stage1() at the end of your puzzle. This reveals the key to the user when all puzzles in the stage has been solved

### CODE REVIEW

**Comment by AlviJawad** [comment]
This needs to be merged fast!!

**Review by Isaac-Wiebe — APPROVED** [review]
Excellent call on setting the key states to hidden or visible.

**Review by johnjegede — APPROVED** [review]
Some how some of the changes I made to puzzle.c showed up in this pull request. it looks good

**Comment by AlviJawad** [comment]
This looks good! Merging without Felix's approval as it is needed for me to work on the next steps.

**Pull request merged**
