### PR TITLE
Added new functionalities to main and some other functions

### LINKED ISSUE #5: Create items
intput the user commands

### LINKED ISSUE #6: Create Location
Create different locations for the game, this is should be part of the objects

### LINKED ISSUE #13: The main function
Write the main function and add functionalities to call some core functions again and again

### LINKED ISSUE #15: Write a function to check the user's bag
Write the execute_check() function

### LINKED ISSUE #16: Write a function to use items from the user's bag
Write the execute_use() function

### LINKED ISSUE #18: Write a function to open locked doors
write the execute_open() function

### PR DESCRIPTION
**Pull request by AlviJawad**
Added new functionalities to main, this fixes #13.

### CODE REVIEW

**Comment by AlviJawad** [comment]
The previous two commits fix #15 and #16.

**Review by johnjegede — APPROVED** [review]
looks good

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
Allow me to upload Object.c

**Review by Isaac-Wiebe — APPROVED** [review]
Everything looks acceptable

**Comment by AlviJawad** [comment]
@felix-elugbaju needs to add functionality to check if the object has a tag that matches the argument

**Review by felix-elugbaju — APPROVED** [review]

**Pull request merged**
