### PR TITLE
Update README for D4

### PR DESCRIPTION
**Pull request by felix-elugbaju**
Added:

- authors
- description
- source files
- build instructions

### CODE REVIEW

**Comment by AlviJawad** [comment]
This is subjective to a lot of changes in the future, we will keep this here.

**Comment by AlviJawad** [comment]
There are conflicts that need to be solved

**Comment by felix-elugbaju** [comment]
@AlviJawad conflicts resolved

**Review by AlviJawad — APPROVED** [review]
Header files and source files might need to be separated (please ask Dr. Martin) and you might need to check for newer changes in the makefile (e.g., make all). Otherwise, looks okay.

**Review by johnjegede — APPROVED** [review]
Nice read me on how to build the project

**Review by Isaac-Wiebe — APPROVED** [review]
Fantastic Update!

**Pull request merged**
