### PR TITLE
New object type <hint> and more intuitive names for keys, doors, and puzzles

### LINKED ISSUE #32: Fix object names door1, key1, puzzle1 etc. to more intuitive names.

### LINKED ISSUE #33: Add the 4th puzzle (1st puzzle for stage2)

### PR DESCRIPTION
**Pull request by AlviJawad**

### CODE REVIEW

**Comment by AlviJawad** [comment]
If you manage to merge Isaac's release1 pull, you should add these changes before doing that!

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
In helper.c, can you add a phrase to the degree of "you might be able to pick up the silver_key?" Otherwise looks fantastic!

**Review by Isaac-Wiebe — APPROVED** [review]

**Comment by AlviJawad** [comment]
This fixes #33

**Review by felix-elugbaju — APPROVED** [review]
👍

**Review by johnjegede — APPROVED** [review]

**Pull request merged**
