### PR TITLE
added objects to stages 1 and 2 and added puzzles for them too

### PR DESCRIPTION
**Pull request by johnjegede**
Created 2 puzzles for stages 1 and 2

### CODE REVIEW

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
See second comment.

**Review by Isaac-Wiebe — CHANGES_REQUESTED** [review]
In include/object.h may you change the name 'bag' to something else i.e. 
treasure_bag to avoid confusion with the 'bag' command defined previously? 
You also defined a paper_puzzle after piano_puzzle in object.h, 
but I see that paper_puzzle is defined before piano_puzzle objects in objects.c. 

My recommendation to keep all the puzzles grouped is to change
paper_puzzle in objs.h as (objs+20)
piano_puzzle as (objs + 21)
and so forth.

Please fix.

**Review by Isaac-Wiebe — APPROVED** [review]
Excellent, things looks like they are in order.

**Comment by johnjegede** [comment]
I have made the right changes

**Review by AlviJawad — APPROVED** [review]
Fine additions.

**Review by felix-elugbaju — APPROVED** [review]

**Review by felix-elugbaju — APPROVED** [review]

**Review by felix-elugbaju — APPROVED** [review]

**Pull request merged**
